### PR TITLE
Add ability to disable OAS compacted emission

### PR DESCRIPTION
**Pull request by postatum**
This PR addresses issues discussed here https://github.com/aml-org/amf/issues/364. In particular it makes possible to disable OAS 2.0, OAS 3.0 "compacted" emission added by this commit https://github.com/aml-org/amf/commit/f4a82948d76b7415e08130bd49f94612d6b39785.

Compacted emission can be disabled with `RenderOptions().withoutCompactedEmission`.

amf-core part of necessary changes is here https://github.com/aml-org/amf-core/pull/116

---

I have few tests failing locally like described below. It may be because I run them with the latest `amf` and `amf-core` and the latter may not be updated to reflect `amf` latest changes. I tried running tests on `amf/develop` with `amf-core/master` and got the same tests failing.

```
[info] - Can parse ABOUT dialect for Flattened form JSON-LD golden *** FAILED ***
[info]   diff -y -W 150 /tmp/1601365633614000128-ABOUT-dialect.flattened.jsonld.tmp amf-client/shared/src/test/resources/vocabularies2/production/ABOUT/ABOUT-dialect.flattened.jsonld
[info]
[info]   3032c3032
[info]   <       "http://a.ml/vocabularies/document-source-maps#value": "[(203,0)-(230,0)]"
[info]   ---
[info]   >       "http://a.ml/vocabularies/document-source-maps#value": "[(202,2)-(230,0)]"
```

```
202  ContributorNode:
203    classTerm: about.Contributor
204    mapping:
205      givenName:
```

---

CI builds fails because `amf-core` PR was not merged/released yet:

```
[error] /home/travis/build/aml-org/amf/amf-webapi/shared/src/main/scala/amf/plugins/document/webapi/OasPlugin.scala:172:17: value isWithCompactedEmission is not a member of amf.core.emitter.RenderOptions

[error]     if (options.isWithCompactedEmission) {
```

### CODE REVIEW

**Comment by AgustinBettati** [comment]
Hello @postatum, the changes look great. For a last detail, we can add some tests in EditingResolutionTest so the resulting api that is emitted can be validated with and without compacted emission.
This can be achieved by adding tests like the following:
```
test("oas api with type definitions referencing each other without compact emission") {
    cycle(
      "type-definitions-with-refs.json",
      "type-definitions-with-refs-no-compact.json",
      OasJsonHint,
      Oas30,
      directory = cyclePath + "oas3/",
      renderOptions = Some(RenderOptions().withoutCompactedEmission),
      transformWith = Some(Oas30)
    )
  }
```
This required you include two new files in the following directory `amf-client/shared/src/test/resources/upanddown/oas3/`, one which is the original api, and the other is the resulting emitted api that is used for validating the test.
The api can simply define two schemas where one is referencing the other, for the case of default emission a ref will be generated and when disabling the compact emission the reference should not be present.
Regarding the tests that where failing, make sure amf is up to date with develop, while aml and core are up to date with master. After doing this and using sourcemode all of the tests should run correctly.

If you have any doubt feel free to leave a comment.

**Comment by postatum** [comment]
Hi @AgustinBettati. Thanks a lot for the detailed notes! 

I've added the tests you described.

> Regarding the tests that where failing, make sure amf is up to date with develop, while aml and core are up to date with master. After doing this and using sourcemode all of the tests should run correctly.

Oh, right, I forgot to pull fresh `amf-aml`.

**Comment by AgustinBettati** [comment]
Thanks for the adjustments.
I have created a branch with your changes in https://github.com/aml-org/amf/pull/676 and https://github.com/aml-org/amf-core/pull/119 so we can proceed with the merge.

**Comment by postatum** [comment]
> Thanks for the adjustments.
> I have created a branch with your changes in #676 and [aml-org/amf-core#119](https://github.com/aml-org/amf-core/pull/119) so we can proceed with the merge.

Amazing. Thanks!

**Comment by AgustinBettati** [comment]
#676 has been merged. The snapshot version (4.4.0-SNAPSHOT) contains these changes, and they will be present in the next release due for the 21st of October.

**Pull request closed without merging**
